### PR TITLE
Dont scroll up when adding/removing transform, fix startPreviewing bug

### LINKED ISSUE #36: Add/remove new transform auto-scrolls up
Add new transform/variation with the + button. the view scrolls up for some reason, moving away from new item
Removing an item also scrolls up

### PR DESCRIPTION
**Pull request by deluksic**
Fixes #36

### CODE REVIEW

File: packages/app/src/utils/createStoreHistory.ts [hunk 1]
```diff
@@ -181,18 +184,30 @@ export function createStoreHistory<T extends object>([store, setStore]: [
     })
   }
 
+  function wrapIntoUndoing(fn: () => void) {
```
Comment (Komediruzecki) [inline packages/app/src/utils/createStoreHistory.ts:187]: Maybe we can have some short comment what is going on here :D

File: packages/app/src/App.tsx [hunk 2]
```diff
@@ -328,7 +328,11 @@ function App(props: { flameFromQuery?: FlameFunction[] }) {
                 max={5000}
                 step={1}
                 onInput={setRenderInterval}
-                formatValue={(value) => `${value.toString()} ms`}
+                formatValue={(value) =>
```
Comment (Komediruzecki) [inline packages/app/src/App.tsx:331]: Looks great now!

File: packages/app/src/utils/createStoreHistory.ts (hunk 1 above)
Comment (deluksic) [reply packages/app/src/utils/createStoreHistory.ts:187]: Will do in a separate MR
