### PR TITLE
Fix exposure factor

### LINKED ISSUE #35: Exposure setting
Fix brightness level of exposure slider on different resolutions

### PR DESCRIPTION
**Pull request by deluksic**
Closes #35

### CODE REVIEW

File: packages/app/src/flame/Flam3.tsx [hunk 1]
```diff
@@ -80,9 +80,12 @@ export function Flam3(props: Flam3Props) {
...
   }
 
-  const factor = createMemo(
-    () => (camera.zoom() * pixelRatio()) ** 2 / (props.pointCount / 1e5),
-  )
+  const factor = createMemo(() => {
+    // height is used because camera.zoom is proportional to
+    // 1 / viewport.height in world-space
+    const { height } = canvasSize()
+    return (0.02 * (camera.zoom() * height) ** 2) / props.pointCount
```
[the remark this answers is not in the document]
Comment (deluksic) [reply packages/app/src/flame/Flam3.tsx:87]: yeah, just something random that works for the default example unfortunately.

**Review by Komediruzecki — APPROVED** [review]

File: packages/app/src/flame/Flam3.tsx [hunk 2]
```diff
@@ -80,9 +80,12 @@ export function Flam3(props: Flam3Props) {
     }
   }
 
-  const factor = createMemo(
-    () => (camera.zoom() * pixelRatio()) ** 2 / (props.pointCount / 1e5),
-  )
+  const factor = createMemo(() => {
```
Comment (Komediruzecki) [inline packages/app/src/flame/Flam3.tsx:83]: Is this exposure factor, maybe we can call it that?

Comment (deluksic) [reply packages/app/src/flame/Flam3.tsx:83]: oh yeah, I'll rename quickly

Comment (deluksic) [reply packages/app/src/flame/Flam3.tsx:83]: well... not exactly, it's more of a count adjustment factor, which keeps the bucket counts similar regardless of zoom level, point counts or resolution

File: packages/app/src/flame/Flam3.tsx (hunk 1 above)
[the remark this answers is not in the document]
Comment (Komediruzecki) [reply packages/app/src/flame/Flam3.tsx:87]: In that case, maybe we can call it something and add a todo to make this better in future?

File: packages/app/src/flame/Flam3.tsx (hunk 2 above)
Comment (deluksic) [reply packages/app/src/flame/Flam3.tsx:83]: exposure is applied after the `pow` curve and this factor is applied before

File: packages/app/src/flame/Flam3.tsx (hunk 1 above)
[the remark this answers is not in the document]
Comment (deluksic) [reply packages/app/src/flame/Flam3.tsx]: Extracted to constant and added a comment.
